// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace epguides
{

    public class Episode
    {

        [JsonProperty("show")]
        public Show Show { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("number")]
        public int Number { get; set; }

        [JsonProperty("season")]
        public int Season { get; set; }

        [JsonProperty("release_date")]
        public string ReleaseDate { get; set; }
    }

}
